import { Component, OnInit, signal } from '@angular/core';
import { CurrencyPipe, DatePipe } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { AuthService } from '../core/auth.service';
import { OrderService } from '../core/order.service';
import { Order } from '../core/models';
import { TranslatePipe } from '../shared/translate.pipe';

@Component({
  standalone: true,
  imports: [CurrencyPipe, DatePipe, ReactiveFormsModule, RouterLink, TranslatePipe],
  template: `
    <section class="account-hero"><div class="container-xxl px-4"><div class="eyebrow">{{ 'Your account' | translate }}</div><h1>{{ 'My account' | translate }}</h1><p>{{ 'Manage your details, favorites, and every order in one place.' | translate }}</p></div></section>
    <section class="account-section"><div class="container-xxl px-4"><div class="row g-5"><aside class="col-lg-3"><div class="account-nav"><button type="button" [class.active]="tab() === 'orders'" (click)="tab.set('orders')"><i class="bi bi-box-seam"></i>{{ 'My orders' | translate }}</button><button type="button" [class.active]="tab() === 'profile'" (click)="tab.set('profile')"><i class="bi bi-person"></i>{{ 'Profile' | translate }}</button><button type="button" [class.active]="tab() === 'security'" (click)="tab.set('security')"><i class="bi bi-shield-lock"></i>{{ 'Security' | translate }}</button><a routerLink="/wishlist"><i class="bi bi-heart"></i>{{ 'Wishlist' | translate }}</a></div></aside>
      <div class="col-lg-9">
        @if (tab() === 'orders') { <div class="account-panel"><div class="panel-heading"><h2>{{ 'My orders' | translate }}</h2><span>{{ orders().length }} {{ 'orders' | translate }}</span></div>@if (loadingOrders()) { <div class="skeleton account-skeleton"></div> } @else if (!orders().length) { <div class="empty-state"><i class="bi bi-box"></i><h3>{{ 'No orders yet' | translate }}</h3><p>{{ 'Your placed orders will appear here.' | translate }}</p><a class="btn btn-ink" routerLink="/products">{{ 'All products' | translate }}</a></div> } @else { <div class="order-list">@for (order of orders(); track order._id) { <article class="account-order"><div class="order-head"><div><small>{{ 'Order' | translate }}</small><strong>#{{ order.orderNumber }}</strong></div><div><small>{{ 'Date' | translate }}</small><span>{{ order.createdAt | date:'mediumDate' }}</span></div><div><small>{{ 'Total' | translate }}</small><span>{{ order.totalPrice | currency }}</span></div><span class="status-badge status-{{ order.status }}">{{ statusLabel(order.status) | translate }}</span></div><div class="order-products">@for (item of order.items; track item.product) { <img [src]="item.imageUrl" [alt]="item.name" [title]="item.name"> }<div class="ms-auto"><a class="btn btn-outline-ink btn-sm" [routerLink]="['/order-confirmation', order._id]">{{ 'Track order' | translate }}</a></div></div></article> }</div> }</div> }
        @if (tab() === 'profile') { <div class="account-panel"><div class="panel-heading"><div><h2>{{ 'Profile details' | translate }}</h2><p>{{ 'Keep your delivery information current.' | translate }}</p></div></div><form class="account-form" [formGroup]="profileForm" (ngSubmit)="saveProfile()"><div class="row g-3"><div class="col-sm-6"><label class="form-label">{{ 'First name' | translate }}</label><input class="form-control" formControlName="firstName"></div><div class="col-sm-6"><label class="form-label">{{ 'Last name' | translate }}</label><input class="form-control" formControlName="lastName"></div><div class="col-12"><label class="form-label">{{ 'Email address' | translate }}</label><input class="form-control" [value]="auth.user()?.email" disabled><small>{{ 'Email changes require support verification.' | translate }}</small></div><div class="col-12"><label class="form-label">{{ 'Phone number' | translate }}</label><input class="form-control" formControlName="phone"></div></div><button class="btn btn-primary-luxe mt-4" type="submit" [disabled]="savingProfile()">{{ 'Save changes' | translate }}</button></form></div> }
        @if (tab() === 'security') { <div class="account-panel"><div class="panel-heading"><div><h2>{{ 'Security' | translate }}</h2><p>{{ 'Use a unique password you do not use elsewhere.' | translate }}</p></div></div><form class="account-form" [formGroup]="passwordForm" (ngSubmit)="savePassword()"><div class="form-group-luxe"><label>{{ 'Current password' | translate }}</label><input class="form-control" type="password" formControlName="currentPassword" autocomplete="current-password"></div><div class="form-group-luxe"><label>{{ 'New password' | translate }}</label><input class="form-control" type="password" formControlName="newPassword" autocomplete="new-password"><small class="form-hint">{{ '10+ characters with uppercase, lowercase, number, and symbol.' | translate }}</small></div><button class="btn btn-primary-luxe" type="submit" [disabled]="savingPassword()">{{ 'Change password' | translate }}</button></form></div> }
      </div></div></div></section>
  `,
})
export class AccountComponent implements OnInit {
  readonly tab = signal<'orders' | 'profile' | 'security'>('orders'); readonly orders = signal<Order[]>([]); readonly loadingOrders = signal(true); readonly savingProfile = signal(false); readonly savingPassword = signal(false); readonly profileForm; readonly passwordForm;
  constructor(public auth: AuthService, private orderService: OrderService, fb: FormBuilder) {
    const user = auth.user(); this.profileForm = fb.nonNullable.group({ firstName: [user?.firstName || '', [Validators.required, Validators.minLength(2)]], lastName: [user?.lastName || '', [Validators.required, Validators.minLength(2)]], phone: [user?.phone || '', Validators.pattern(/^\+?[0-9]{10,15}$/)] }); this.passwordForm = fb.nonNullable.group({ currentPassword: ['', Validators.required], newPassword: ['', [Validators.required, Validators.pattern(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{10,72}$/)]] });
  }
  ngOnInit(): void { this.orderService.mine().subscribe({ next: (orders) => { this.orders.set(orders); this.loadingOrders.set(false); }, error: () => this.loadingOrders.set(false) }); }
  statusLabel(status: string): string { return ({ ordered: 'Ordered', processing: 'Processing', shipped: 'Shipped', delivered: 'Delivered', cancelled: 'Cancelled' } as Record<string, string>)[status] || status; }
  saveProfile(): void { if (this.profileForm.invalid) { this.profileForm.markAllAsTouched(); return; } this.savingProfile.set(true); this.auth.updateProfile(this.profileForm.getRawValue()).subscribe({ next: () => this.savingProfile.set(false), error: () => this.savingProfile.set(false) }); }
  savePassword(): void { if (this.passwordForm.invalid) { this.passwordForm.markAllAsTouched(); return; } this.savingPassword.set(true); this.auth.changePassword(this.passwordForm.getRawValue()).subscribe({ next: () => { this.passwordForm.reset(); this.savingPassword.set(false); }, error: () => this.savingPassword.set(false) }); }
}
