import { DatePipe } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AdminService } from '../core/admin.service';
import { SupportSettings, SupportTicket, SupportTicketStatus } from '../core/models';
import { ToastService } from '../core/toast.service';
import { TranslatePipe } from '../shared/translate.pipe';

@Component({
  standalone: true,
  imports: [DatePipe, ReactiveFormsModule, TranslatePipe],
  template: `
    <div class="admin-page-heading"><div><h1>{{ 'Support centre' | translate }}</h1><p>{{ 'Manage customer tickets and the contact information shown on the storefront.' | translate }}</p></div><button class="btn btn-primary-luxe" type="button" (click)="saveSettings()" [disabled]="settingsForm.invalid || savingSettings()"><i class="bi bi-cloud-check me-2"></i>{{ (savingSettings() ? 'Saving...' : 'Save contact details') | translate }}</button></div>
    <div class="row g-4"><div class="col-xl-4"><section class="admin-card support-settings-card"><div class="admin-card-head"><div><h2>{{ 'Store contact details' | translate }}</h2><p>{{ 'Customers see these details on the support page.' | translate }}</p></div></div><form [formGroup]="settingsForm" (ngSubmit)="saveSettings()"><div class="form-group-luxe"><label for="adminSupportEmail">{{ 'Support email' | translate }} *</label><input id="adminSupportEmail" class="form-control" type="email" formControlName="email"></div><div class="form-group-luxe"><label for="adminSupportPhone">{{ 'Support phone' | translate }} *</label><input id="adminSupportPhone" class="form-control" formControlName="phone"></div><div class="form-group-luxe"><label for="adminSupportHours">{{ 'Support hours' | translate }}</label><textarea id="adminSupportHours" class="form-control" rows="3" formControlName="hours" maxlength="160"></textarea></div><button class="btn btn-primary-luxe w-100" type="submit" [disabled]="settingsForm.invalid || savingSettings()">{{ 'Save contact details' | translate }}</button></form></section></div>
    <div class="col-xl-8"><div class="ticket-metric-grid"><article><i class="bi bi-inbox"></i><div><strong>{{ count('open') }}</strong><span>{{ 'Open' | translate }}</span></div></article><article><i class="bi bi-arrow-repeat"></i><div><strong>{{ count('in_progress') }}</strong><span>{{ 'In progress' | translate }}</span></div></article><article><i class="bi bi-check2-circle"></i><div><strong>{{ count('resolved') }}</strong><span>{{ 'Resolved' | translate }}</span></div></article></div><section class="admin-card mt-4"><div class="admin-card-head"><div><h2>{{ 'Customer tickets' | translate }}</h2><p>{{ 'Newest requests appear first.' | translate }}</p></div><select class="form-select ticket-filter" [value]="filter()" (change)="changeFilter($event)"><option value="all">{{ 'All statuses' | translate }}</option><option value="open">{{ 'Open' | translate }}</option><option value="in_progress">{{ 'In progress' | translate }}</option><option value="resolved">{{ 'Resolved' | translate }}</option></select></div><div class="admin-ticket-list">@for (ticket of tickets(); track ticket._id) { <button type="button" (click)="openTicket(ticket)"><span class="ticket-priority-dot status-{{ ticket.status }}"></span><div><strong>{{ ticket.subject }}</strong><small>#{{ ticket.ticketNumber }} · {{ ticket.name }} · {{ ticket.createdAt | date:'medium' }}</small></div><span class="ticket-status status-{{ ticket.status }}">{{ statusLabel(ticket.status) | translate }}</span><i class="bi bi-chevron-right"></i></button> } @empty { <div class="empty-state"><i class="bi bi-inbox"></i><p>{{ 'No support tickets in this view.' | translate }}</p></div> }</div></section></div></div>

    @if (selectedTicket(); as ticket) { <div class="drawer-backdrop" (click)="closeTicket()"></div><aside class="admin-drawer support-ticket-drawer"><div class="drawer-head"><div><div class="eyebrow">#{{ ticket.ticketNumber }}</div><h2>{{ ticket.subject }}</h2></div><button type="button" (click)="closeTicket()"><i class="bi bi-x-lg"></i></button></div><div class="ticket-customer-card"><div><i class="bi bi-person"></i><span><small>{{ 'Customer' | translate }}</small><strong>{{ ticket.name }}</strong></span></div><a [href]="'mailto:' + ticket.email"><i class="bi bi-envelope"></i>{{ ticket.email }}</a>@if (ticket.phone) { <a [href]="'tel:' + ticket.phone"><i class="bi bi-telephone"></i>{{ ticket.phone }}</a> }</div><div class="ticket-message"><span>{{ categoryLabel(ticket.category) | translate }} · {{ ticket.createdAt | date:'medium' }}</span><p>{{ ticket.message }}</p></div><form [formGroup]="ticketForm" (ngSubmit)="saveTicket()"><div class="form-group-luxe"><label for="ticketStatus">{{ 'Ticket status' | translate }}</label><select id="ticketStatus" class="form-select" formControlName="status"><option value="open">{{ 'Open' | translate }}</option><option value="in_progress">{{ 'In progress' | translate }}</option><option value="resolved">{{ 'Resolved' | translate }}</option></select></div><div class="form-group-luxe"><label for="ticketNote">{{ 'Admin response note' | translate }}</label><textarea id="ticketNote" class="form-control" rows="6" formControlName="adminNote" maxlength="2000"></textarea><small class="form-hint">{{ 'This note is visible to the signed-in customer.' | translate }}</small></div><button class="btn btn-primary-luxe w-100" type="submit" [disabled]="ticketForm.invalid || savingTicket()">{{ (savingTicket() ? 'Saving...' : 'Update ticket') | translate }}</button></form></aside> }
  `,
})
export class AdminSupportComponent implements OnInit {
  readonly settings = signal<SupportSettings>({ email: '', phone: '', hours: '' });
  readonly tickets = signal<SupportTicket[]>([]);
  readonly allTickets = signal<SupportTicket[]>([]);
  readonly selectedTicket = signal<SupportTicket | null>(null);
  readonly filter = signal<SupportTicketStatus | 'all'>('all');
  readonly savingSettings = signal(false);
  readonly savingTicket = signal(false);
  readonly settingsForm;
  readonly ticketForm;
  constructor(private admin: AdminService, private toast: ToastService, fb: FormBuilder) { this.settingsForm = fb.nonNullable.group({ email: ['', [Validators.required, Validators.email, Validators.maxLength(160)]], phone: ['', [Validators.required, Validators.minLength(5), Validators.maxLength(30)]], hours: ['', Validators.maxLength(160)] }); this.ticketForm = fb.nonNullable.group({ status: ['open' as SupportTicketStatus, Validators.required], adminNote: ['', Validators.maxLength(2000)] }); }
  ngOnInit(): void { this.load(); }
  load(): void { this.admin.support('all').subscribe((data) => { this.settings.set(data.settings); this.settingsForm.reset(data.settings); this.allTickets.set(data.tickets); this.applyFilter(); }); }
  count(status: SupportTicketStatus): number { return this.allTickets().filter((ticket) => ticket.status === status).length; }
  changeFilter(event: Event): void { this.filter.set((event.target as HTMLSelectElement).value as SupportTicketStatus | 'all'); this.applyFilter(); }
  applyFilter(): void { this.tickets.set(this.filter() === 'all' ? this.allTickets() : this.allTickets().filter((ticket) => ticket.status === this.filter())); }
  saveSettings(): void { if (this.settingsForm.invalid || this.savingSettings()) return; this.savingSettings.set(true); this.admin.saveSupportSettings(this.settingsForm.getRawValue()).subscribe({ next: (settings) => { this.settings.set(settings); this.savingSettings.set(false); this.toast.success('Support contact details saved'); }, error: () => this.savingSettings.set(false) }); }
  openTicket(ticket: SupportTicket): void { this.selectedTicket.set(ticket); this.ticketForm.reset({ status: ticket.status, adminNote: ticket.adminNote || '' }); }
  closeTicket(): void { if (!this.savingTicket()) this.selectedTicket.set(null); }
  saveTicket(): void { const ticket = this.selectedTicket(); if (!ticket || this.ticketForm.invalid || this.savingTicket()) return; this.savingTicket.set(true); this.admin.updateSupportTicket(ticket._id, this.ticketForm.getRawValue()).subscribe({ next: (updated) => { this.allTickets.update((items) => items.map((item) => item._id === updated._id ? updated : item)); this.applyFilter(); this.selectedTicket.set(updated); this.savingTicket.set(false); this.toast.success('Ticket updated'); }, error: () => this.savingTicket.set(false) }); }
  statusLabel(status: SupportTicketStatus): string { return ({ open: 'Open', in_progress: 'In progress', resolved: 'Resolved' })[status]; }
  categoryLabel(category: SupportTicket['category']): string { return ({ order: 'Order', product: 'Product', delivery: 'Delivery', return: 'Return or exchange', account: 'Account', other: 'Other' })[category]; }
}
