import { CurrencyPipe, DatePipe, DecimalPipe } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { AdminService, DashboardData } from '../core/admin.service';
import { TranslatePipe } from '../shared/translate.pipe';

@Component({
  standalone: true,
  imports: [CurrencyPipe, DatePipe, DecimalPipe, RouterLink, TranslatePipe],
  template: `
    <div class="admin-page-heading"><div><h1>{{ 'Sales dashboard' | translate }}</h1><p>{{ 'Revenue, profit, orders, customers, and inventory in one operational view.' | translate }}</p></div><a class="btn btn-primary-luxe" routerLink="/admin/products"><i class="bi bi-plus-lg me-2"></i>{{ 'Add product' | translate }}</a></div>
    @if (loading()) { <div class="skeleton admin-dashboard-skeleton"></div> }
    @else if (data(); as dashboard) {
      <div class="metric-grid financial-metrics">
        <article><div><small>{{ 'Total revenue' | translate }}</small><strong>{{ dashboard.totalRevenue | currency }}</strong><span class="positive"><i class="bi bi-graph-up-arrow"></i>{{ dashboard.ordersCount }} {{ 'orders' | translate }}</span></div><i class="bi bi-wallet2"></i></article>
        <article class="profit-metric"><div><small>{{ 'Gross profit' | translate }}</small><strong>{{ dashboard.grossProfit | currency }}</strong><span class="positive">{{ dashboard.profitMargin | number:'1.0-1' }}% {{ 'margin' | translate }}</span></div><i class="bi bi-piggy-bank"></i></article>
        <article><div><small>{{ 'Average order value' | translate }}</small><strong>{{ dashboard.averageOrderValue | currency }}</strong><span>{{ dashboard.unitsSold }} {{ 'units sold' | translate }}</span></div><i class="bi bi-receipt"></i></article>
        <article><div><small>{{ 'Customers' | translate }}</small><strong>{{ dashboard.usersCount }}</strong><span>{{ 'Registered accounts' | translate }}</span></div><i class="bi bi-people"></i></article>
        <article class="danger-metric"><div><small>{{ 'Unavailable products' | translate }}</small><strong>{{ dashboard.inventory.unavailableProducts }}</strong><span>{{ dashboard.lowStockProducts.length }} {{ 'need attention' | translate }}</span></div><i class="bi bi-exclamation-triangle"></i></article>
      </div>

      <div class="analytics-summary-grid mt-4"><article><small>{{ 'Product sales' | translate }}</small><strong>{{ dashboard.productRevenue | currency }}</strong></article><article><small>{{ 'Cost of goods' | translate }}</small><strong>{{ dashboard.costOfGoods | currency }}</strong></article><article><small>{{ 'Shipping collected' | translate }}</small><strong>{{ dashboard.shippingRevenue | currency }}</strong></article><article><small>{{ 'Delivered revenue' | translate }}</small><strong>{{ dashboard.deliveredRevenue | currency }}</strong></article><article><small>{{ 'Cancelled value' | translate }}</small><strong>{{ dashboard.cancelledValue | currency }}</strong><span>{{ dashboard.cancelledOrders }} {{ 'orders' | translate }}</span></article><article><small>{{ 'Inventory retail value' | translate }}</small><strong>{{ dashboard.inventory.retailValue | currency }}</strong><span>{{ dashboard.inventory.units }} {{ 'units' | translate }}</span></article></div>

      <div class="row g-4 mt-1"><div class="col-xl-8"><section class="admin-card sales-chart-card"><div class="admin-card-head"><div><h2>{{ 'Six-month sales performance' | translate }}</h2><p>{{ 'Revenue and gross profit by order month.' | translate }}</p></div><div class="chart-legend"><span><i class="revenue-dot"></i>{{ 'Revenue' | translate }}</span><span><i class="profit-dot"></i>{{ 'Profit' | translate }}</span></div></div>@if (dashboard.monthlySales.length) { <div class="sales-chart">@for (month of dashboard.monthlySales; track month.month) { <div class="sales-column"><div class="sales-values"><strong>{{ month.revenue | currency:'USD':'symbol':'1.0-0' }}</strong><small>{{ month.orders }} {{ 'orders' | translate }}</small></div><div class="sales-bars"><span class="revenue-bar" [style.height.%]="chartHeight(month.revenue, dashboard)"></span><span class="profit-bar" [style.height.%]="chartHeight(month.profit, dashboard)"></span></div><label>{{ monthLabel(month.month) }}</label></div> }</div> } @else { <div class="empty-state compact"><i class="bi bi-bar-chart"></i><p>{{ 'Sales will appear after the first order.' | translate }}</p></div> }</section></div><div class="col-xl-4"><section class="admin-card h-100"><div class="admin-card-head"><h2>{{ 'Order status mix' | translate }}</h2></div><div class="status-breakdown">@for (status of dashboard.statusBreakdown; track status.status) { <article><div><span class="status-badge status-{{ status.status }}">{{ statusLabel(status.status) | translate }}</span><small>{{ status.value | currency }}</small></div><strong>{{ status.count }}</strong></article> } @empty { <div class="empty-state compact">{{ 'No orders yet' | translate }}</div> }</div></section></div></div>

      <div class="row g-4 mt-1"><div class="col-xl-8"><section class="admin-card"><div class="admin-card-head"><h2>{{ 'Recent orders' | translate }}</h2><a routerLink="/admin/orders">{{ 'View all' | translate }} <i class="bi bi-arrow-right"></i></a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>{{ 'Order' | translate }}</th><th>{{ 'Customers' | translate }}</th><th>{{ 'Date' | translate }}</th><th>{{ 'Total' | translate }}</th><th>{{ 'Status' | translate }}</th></tr></thead><tbody>@for (order of dashboard.recentOrders; track order._id) { <tr><td><strong>#{{ order.orderNumber }}</strong></td><td>{{ customerName(order.user) }}</td><td>{{ order.createdAt | date:'mediumDate' }}</td><td>{{ order.totalPrice | currency }}</td><td><span class="status-badge status-{{ order.status }}">{{ statusLabel(order.status) | translate }}</span></td></tr> } @empty { <tr><td colspan="5" class="text-center py-5 text-secondary">{{ 'No orders yet' | translate }}</td></tr> }</tbody></table></div></section><section class="admin-card mt-4"><div class="admin-card-head"><h2>{{ 'Latest products' | translate }}</h2><a routerLink="/admin/products">{{ 'Manage catalog' | translate }}</a></div><div class="latest-product-grid">@for (product of dashboard.latestProducts; track product._id) { <article><img [src]="product.imageUrl" [alt]="product.name"><div><strong>{{ product.name }}</strong><span>{{ product.price | currency }}</span><small [class.low-stock]="product.stock <= 5">{{ 'Stock' | translate }}: {{ product.stock }}</small></div></article> }</div></section></div>
      <div class="col-xl-4"><section class="admin-card h-100"><div class="admin-card-head"><h2><i class="bi bi-exclamation-triangle me-2"></i>{{ 'Stock alerts' | translate }}</h2></div><div class="inventory-value-card"><small>{{ 'Inventory cost value' | translate }}</small><strong>{{ dashboard.inventory.costValue | currency }}</strong><span>{{ dashboard.inventory.units }} {{ 'units on hand' | translate }}</span></div><div class="low-stock-list mt-3">@for (product of dashboard.lowStockProducts; track product._id) { <article><img [src]="product.imageUrl" [alt]="product.name"><div><strong>{{ product.name }}</strong><small>{{ product.isManuallyUnavailable ? ('Manual override' | translate) : (product.stock + ' ' + ('remaining' | translate)) }}</small></div><a routerLink="/admin/products"><i class="bi bi-pencil"></i></a></article> } @empty { <div class="empty-state compact"><i class="bi bi-check-circle"></i><p>{{ 'All stock levels look healthy.' | translate }}</p></div> }</div></section></div></div>
    }
  `,
})
export class AdminDashboardComponent implements OnInit {
  readonly data = signal<DashboardData | null>(null);
  readonly loading = signal(true);
  constructor(private admin: AdminService) {}
  ngOnInit(): void { this.admin.dashboard().subscribe({ next: (data) => { this.data.set(data); this.loading.set(false); }, error: () => this.loading.set(false) }); }
  customerName(user: unknown): string { const value = user as { firstName?: string; lastName?: string }; return value?.firstName ? `${value.firstName} ${value.lastName}` : 'Customer'; }
  statusLabel(status: string): string { return ({ ordered: 'Ordered', processing: 'Processing', shipped: 'Shipped', delivered: 'Delivered', cancelled: 'Cancelled' } as Record<string, string>)[status] || status; }
  monthLabel(month: string): string { return new Intl.DateTimeFormat('en', { month: 'short' }).format(new Date(`${month}-02T00:00:00Z`)); }
  chartHeight(value: number, dashboard: DashboardData): number { const max = Math.max(...dashboard.monthlySales.map((item) => item.revenue), 1); return Math.max(4, Math.min(100, (value / max) * 100)); }
}
