import { Component, OnInit, signal } from '@angular/core';
import { CurrencyPipe, TitleCasePipe } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Product } from '../core/models';
import { ProductService } from '../core/product.service';
import { ToastService } from '../core/toast.service';
import { TranslatePipe } from '../shared/translate.pipe';

@Component({
  standalone: true,
  imports: [CurrencyPipe, TitleCasePipe, ReactiveFormsModule, TranslatePipe],
  template: `
    <div class="admin-page-heading"><div><h1>{{ 'Products' | translate }}</h1><p>{{ 'Create, edit, price, and manage catalog availability.' | translate }}</p></div><button class="btn btn-primary-luxe" type="button" (click)="openCreate()"><i class="bi bi-plus-lg me-2"></i>{{ 'Add product' | translate }}</button></div>
    <section class="admin-card"><div class="admin-card-head admin-search-head"><form (submit)="searchProducts($event)"><i class="bi bi-search"></i><input type="search" [placeholder]="'Search catalog' | translate" [value]="search()" (input)="search.set($any($event.target).value)"></form><span>{{ products().length }} {{ 'products' | translate }}</span></div><div class="table-responsive"><table class="table align-middle product-admin-table"><thead><tr><th>{{ 'Product' | translate }}</th><th>{{ 'Category' | translate }}</th><th>{{ 'Price' | translate }}</th><th>{{ 'Stock' | translate }}</th><th>{{ 'Featured' | translate }}</th><th class="text-end">{{ 'Actions' | translate }}</th></tr></thead><tbody>@for (product of products(); track product._id) { <tr><td><div class="admin-product-cell"><img [src]="product.imageUrl" [alt]="product.name"><div><strong>{{ product.name }}</strong><small>{{ (product.collection || 'Core catalog') | titlecase }}</small></div></div></td><td>{{ product.category | titlecase }}</td><td>{{ product.price | currency }}</td><td><span [class.low-stock]="product.stock <= 5">{{ product.stock }}</span></td><td><i class="bi" [class.bi-star-fill]="product.featured" [class.bi-star]="!product.featured"></i></td><td class="text-end"><button class="btn btn-sm btn-outline-secondary me-2" type="button" (click)="openEdit(product)" [attr.aria-label]="'Edit' | translate"><i class="bi bi-pencil"></i></button><button class="btn btn-sm btn-outline-danger" type="button" (click)="remove(product)" [attr.aria-label]="'Delete' | translate"><i class="bi bi-trash"></i></button></td></tr> } @empty { <tr><td colspan="6"><div class="empty-state compact">{{ 'No products found' | translate }}.</div></td></tr> }</tbody></table></div></section>
    @if (formOpen()) { <div class="drawer-backdrop" (click)="closeForm()"></div><aside class="admin-drawer"><div class="drawer-head"><div><div class="eyebrow">{{ 'Catalog editor' | translate }}</div><h2>{{ (editing() ? 'Edit product' : 'New product') | translate }}</h2></div><button type="button" (click)="closeForm()"><i class="bi bi-x-lg"></i></button></div><form [formGroup]="form" (ngSubmit)="save()"><div class="form-group-luxe"><label>{{ 'Name' | translate }}</label><input class="form-control" formControlName="name"></div><div class="form-group-luxe"><label>{{ 'Description' | translate }}</label><textarea class="form-control" rows="4" formControlName="description"></textarea></div><div class="row g-3"><div class="col-6"><div class="form-group-luxe"><label>{{ 'Category' | translate }}</label><input class="form-control" formControlName="category"></div></div><div class="col-6"><div class="form-group-luxe"><label>{{ 'Collection' | translate }}</label><input class="form-control" formControlName="collection"></div></div></div><div class="row g-3"><div class="col-4"><div class="form-group-luxe"><label>{{ 'Price' | translate }}</label><input class="form-control" type="number" min="0" formControlName="price"></div></div><div class="col-4"><div class="form-group-luxe"><label>{{ 'Old price' | translate }}</label><input class="form-control" type="number" min="0" formControlName="oldPrice"></div></div><div class="col-4"><div class="form-group-luxe"><label>{{ 'Stock' | translate }}</label><input class="form-control" type="number" min="0" formControlName="stock"></div></div></div><div class="form-group-luxe"><label>{{ 'Image path or HTTPS URL' | translate }}</label><input class="form-control" formControlName="imageUrl"><small class="form-hint">{{ 'Use /assets/... for bundled images.' | translate }}</small></div><div class="d-flex gap-4 mb-4"><label class="form-check"><input class="form-check-input" type="checkbox" formControlName="featured"><span class="form-check-label">{{ 'Featured' | translate }}</span></label><label class="form-check"><input class="form-check-input" type="checkbox" formControlName="isNewArrival"><span class="form-check-label">{{ 'New arrival' | translate }}</span></label></div><div class="d-flex gap-2"><button class="btn btn-primary-luxe flex-grow-1" type="submit" [disabled]="saving()">{{ (saving() ? 'Saving...' : 'Save product') | translate }}</button><button class="btn btn-outline-ink" type="button" (click)="closeForm()">{{ 'Cancel' | translate }}</button></div></form></aside> }
  `,
})
export class AdminProductsComponent implements OnInit {
  readonly products = signal<Product[]>([]); readonly search = signal(''); readonly formOpen = signal(false); readonly editing = signal<Product | null>(null); readonly saving = signal(false); readonly form;
  constructor(private api: ProductService, private toast: ToastService, fb: FormBuilder) { this.form = fb.nonNullable.group({ name: ['', [Validators.required, Validators.minLength(2)]], description: ['', [Validators.required, Validators.minLength(20)]], category: ['', Validators.required], collection: [''], price: [0, [Validators.required, Validators.min(0)]], oldPrice: [0], stock: [0, [Validators.required, Validators.min(0)]], imageUrl: ['/assets/catalog/catalog-01.jpg', [Validators.required, Validators.pattern(/^(\/assets\/|https:\/\/)/)]], featured: [false], isNewArrival: [false], gallery: [[] as string[]], rating: [4.8], reviewsCount: [0] }); }
  ngOnInit(): void { this.load(); }
  load(search = ''): void { this.api.list({ search, limit: 48, sort: 'newest' }).subscribe((response) => this.products.set(response.data.products)); }
  searchProducts(event: Event): void { event.preventDefault(); this.load(this.search()); }
  openCreate(): void { this.editing.set(null); this.form.reset({ name: '', description: '', category: '', collection: '', price: 0, oldPrice: 0, stock: 0, imageUrl: '/assets/catalog/catalog-01.jpg', featured: false, isNewArrival: false, gallery: [], rating: 4.8, reviewsCount: 0 }); this.formOpen.set(true); }
  openEdit(product: Product): void { this.editing.set(product); this.form.patchValue({ ...product, oldPrice: product.oldPrice || 0 }); this.formOpen.set(true); }
  closeForm(): void { this.formOpen.set(false); this.editing.set(null); }
  save(): void { if (this.form.invalid) { this.form.markAllAsTouched(); return; } this.saving.set(true); const payload = { ...this.form.getRawValue(), oldPrice: this.form.value.oldPrice || null }; const request = this.editing() ? this.api.update(this.editing()!._id, payload) : this.api.create(payload); request.subscribe({ next: (response) => { this.toast.success(response.message || 'Product saved'); this.saving.set(false); this.closeForm(); this.load(this.search()); }, error: () => this.saving.set(false) }); }
  remove(product: Product): void { if (!window.confirm(`Delete ${product.name}? This cannot be undone.`)) return; this.api.remove(product._id).subscribe(() => { this.toast.info('Product deleted'); this.products.update((items) => items.filter((item) => item._id !== product._id)); }); }
}
