import { CurrencyPipe, DatePipe } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { AdminService, DashboardData } from '../core/admin.service';
import { TranslatePipe } from '../shared/translate.pipe';

@Component({
  standalone: true,
  imports: [CurrencyPipe, DatePipe, RouterLink, TranslatePipe],
  template: `
    <div class="admin-page-heading"><div><h1>{{ 'Sales dashboard' | translate }}</h1><p>{{ 'Online and store revenue, customer debts, orders, and inventory in one view.' | translate }}</p></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-ink" routerLink="/admin/products" [queryParams]="{manage:'categories'}"><i class="bi bi-tags me-2"></i>{{ 'Manage categories' | translate }}</a><a class="btn btn-outline-ink" routerLink="/admin/offline-sales"><i class="bi bi-receipt-cutoff me-2"></i>{{ 'Record store sale' | translate }}</a><a class="btn btn-primary-luxe" routerLink="/admin/products"><i class="bi bi-plus-lg me-2"></i>{{ 'Add product' | translate }}</a></div></div>
    @if (loading()) { <div class="skeleton admin-dashboard-skeleton"></div> }
    @else if (data(); as dashboard) {
      <div class="metric-grid financial-metrics">
        <article><div><small>{{ 'Total revenue' | translate }}</small><strong>{{ dashboard.totalRevenue | currency }}</strong><span>{{ dashboard.totalTransactions }} {{ 'sales' | translate }}</span></div><i class="bi bi-wallet2"></i></article>
        <article><div><small>{{ 'Online revenue' | translate }}</small><strong>{{ dashboard.onlineRevenue | currency }}</strong><span>{{ dashboard.ordersCount }} {{ 'orders' | translate }}</span></div><i class="bi bi-globe2"></i></article>
        <article><div><small>{{ 'Store revenue' | translate }}</small><strong>{{ dashboard.offlineRevenue | currency }}</strong><span>{{ dashboard.offlineSalesCount }} {{ 'counter sales' | translate }}</span></div><i class="bi bi-shop-window"></i></article>
        <article class="debt-metric"><div><small>{{ 'Outstanding debt' | translate }}</small><strong>{{ dashboard.outstandingDebt | currency }}</strong><span>{{ dashboard.highestDebts.length }} {{ 'debt accounts' | translate }}</span></div><i class="bi bi-hourglass-split"></i></article>
        <article><div><small>{{ 'Customers' | translate }}</small><strong>{{ dashboard.usersCount }}</strong><span>{{ 'Registered accounts' | translate }}</span></div><i class="bi bi-people"></i></article>
      </div>

      <div class="analytics-summary-grid revenue-summary-grid mt-4"><article><small>{{ 'Store payments collected' | translate }}</small><strong>{{ dashboard.collectedOfflineRevenue | currency }}</strong></article><article><small>{{ 'Average sale value' | translate }}</small><strong>{{ dashboard.averageSaleValue | currency }}</strong></article><article><small>{{ 'Units sold' | translate }}</small><strong>{{ dashboard.unitsSold }}</strong></article><article><small>{{ 'Delivered online revenue' | translate }}</small><strong>{{ dashboard.deliveredRevenue | currency }}</strong></article><article><small>{{ 'Inventory retail value' | translate }}</small><strong>{{ dashboard.inventory.retailValue | currency }}</strong><span>{{ dashboard.inventory.units }} {{ 'units' | translate }}</span></article></div>

      <div class="row g-4 mt-1"><div class="col-xl-8"><section class="admin-card sales-chart-card"><div class="admin-card-head"><div><h2>{{ 'Six-month revenue' | translate }}</h2><p>{{ 'Online and in-store sales by month.' | translate }}</p></div><div class="chart-legend"><span><i class="revenue-dot"></i>{{ 'Online' | translate }}</span><span><i class="store-revenue-dot"></i>{{ 'In store' | translate }}</span></div></div>@if (dashboard.monthlySales.length) { <div class="sales-chart">@for (month of dashboard.monthlySales; track month.month) { <div class="sales-column"><div class="sales-values"><strong>{{ month.revenue | currency:'EGP':'symbol':'1.0-0' }}</strong><small>{{ month.sales }} {{ 'sales' | translate }}</small></div><div class="sales-bars"><span class="revenue-bar" [style.height.%]="chartHeight(month.onlineRevenue, dashboard)"></span><span class="store-revenue-bar" [style.height.%]="chartHeight(month.offlineRevenue, dashboard)"></span></div><label>{{ monthLabel(month.month) }}</label></div> }</div> } @else { <div class="empty-state compact"><i class="bi bi-bar-chart"></i><p>{{ 'Sales will appear after the first transaction.' | translate }}</p></div> }</section></div><div class="col-xl-4"><section class="admin-card h-100"><div class="admin-card-head"><div><h2>{{ 'Highest customer debts' | translate }}</h2><p>{{ 'Balances that need collection.' | translate }}</p></div><a routerLink="/admin/offline-sales">{{ 'View ledger' | translate }}</a></div><div class="dashboard-debt-list">@for (debtor of dashboard.highestDebts; track debtor._id) { <article><div><strong>{{ debtor.customerName }}</strong><small>{{ debtor.lastActivityAt | date:'mediumDate' }}</small></div><b>{{ debtor.balanceDue | currency }}</b></article> } @empty { <div class="empty-state compact"><i class="bi bi-check-circle"></i><p>{{ 'No outstanding customer debt.' | translate }}</p></div> }</div></section></div></div>

      <section class="admin-card mt-4 product-sales-card"><div class="admin-card-head"><div><h2>{{ 'Product sales performance' | translate }}</h2><p>{{ 'Units sold for every product across online orders and store sales.' | translate }}</p></div><span>{{ dashboard.productSales.length }} {{ 'products' | translate }}</span></div><div class="product-sales-list">@for (product of dashboard.productSales; track product.productId || product.productName) { <article>@if (product.imageUrl) { <img [src]="product.imageUrl" [alt]="product.productName"> } @else { <span class="product-sales-placeholder"><i class="bi bi-bag"></i></span> }<div class="product-sales-name"><strong>{{ product.productName }}</strong><small>{{ product.revenue | currency }} {{ 'revenue' | translate }}</small></div><div class="product-sales-bar"><span [style.width.%]="productSalesWidth(product.totalUnits, dashboard)"></span></div><div class="product-sales-units"><strong>{{ product.totalUnits }}</strong><small>{{ 'units sold' | translate }}</small></div><div class="product-sales-split"><span>{{ product.onlineUnits }} {{ 'online' | translate }}</span><span>{{ product.offlineUnits }} {{ 'in store' | translate }}</span></div></article> } @empty { <div class="empty-state compact"><i class="bi bi-bar-chart"></i><p>{{ 'Product sales will appear after the first transaction.' | translate }}</p></div> }</div></section>

      <div class="row g-4 mt-1"><div class="col-xl-8"><section class="admin-card"><div class="admin-card-head"><h2>{{ 'Recent orders' | translate }}</h2><a routerLink="/admin/orders">{{ 'View all' | translate }} <i class="bi bi-arrow-right"></i></a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>{{ 'Order' | translate }}</th><th>{{ 'Customers' | translate }}</th><th>{{ 'Date' | translate }}</th><th>{{ 'Total' | translate }}</th><th>{{ 'Status' | translate }}</th></tr></thead><tbody>@for (order of dashboard.recentOrders; track order._id) { <tr><td><strong>#{{ order.orderNumber }}</strong></td><td>{{ customerName(order.user) }}</td><td>{{ order.createdAt | date:'mediumDate' }}</td><td>{{ order.totalPrice | currency }}</td><td><span class="status-badge status-{{ order.status }}">{{ statusLabel(order.status) | translate }}</span></td></tr> } @empty { <tr><td colspan="5" class="text-center py-5 text-secondary">{{ 'No orders yet' | translate }}</td></tr> }</tbody></table></div></section><section class="admin-card mt-4"><div class="admin-card-head"><h2>{{ 'Latest products' | translate }}</h2><a routerLink="/admin/products">{{ 'Manage catalog' | translate }}</a></div><div class="latest-product-grid">@for (product of dashboard.latestProducts; track product._id) { <article><img [src]="product.imageUrl" [alt]="product.name"><div><strong>{{ product.name }}</strong><span>{{ product.price | currency }}</span><small [class.low-stock]="product.stock <= 5">{{ 'Stock' | translate }}: {{ product.stock }}</small></div></article> }</div></section></div>
      <div class="col-xl-4"><section class="admin-card h-100"><div class="admin-card-head"><h2><i class="bi bi-exclamation-triangle me-2"></i>{{ 'Stock alerts' | translate }}</h2></div><div class="inventory-value-card"><small>{{ 'Inventory retail value' | translate }}</small><strong>{{ dashboard.inventory.retailValue | currency }}</strong><span>{{ dashboard.inventory.units }} {{ 'units on hand' | translate }}</span></div><div class="low-stock-list mt-3">@for (product of dashboard.lowStockProducts; track product._id) { <article><img [src]="product.imageUrl" [alt]="product.name"><div><strong>{{ product.name }}</strong><small>{{ product.isManuallyUnavailable ? ('Manual override' | translate) : (product.stock + ' ' + ('remaining' | translate)) }}</small></div><a routerLink="/admin/products"><i class="bi bi-pencil"></i></a></article> } @empty { <div class="empty-state compact"><i class="bi bi-check-circle"></i><p>{{ 'All stock levels look healthy.' | translate }}</p></div> }</div></section></div></div>
    }
  `,
})
export class AdminDashboardComponent implements OnInit {
  readonly data = signal<DashboardData | null>(null);
  readonly loading = signal(true);
  constructor(private admin: AdminService) {}
  ngOnInit(): void { this.admin.dashboard().subscribe({ next: (data) => { this.data.set(data); this.loading.set(false); }, error: () => this.loading.set(false) }); }
  customerName(user: unknown): string { const value = user as { firstName?: string; lastName?: string }; return value?.firstName ? `${value.firstName} ${value.lastName}` : 'Customer'; }
  statusLabel(status: string): string { return ({ ordered: 'Ordered', processing: 'Processing', shipped: 'Shipped', delivered: 'Delivered', cancelled: 'Cancelled' } as Record<string, string>)[status] || status; }
  monthLabel(month: string): string { return new Intl.DateTimeFormat('en', { month: 'short' }).format(new Date(`${month}-02T00:00:00Z`)); }
  chartHeight(value: number, dashboard: DashboardData): number { const max = Math.max(...dashboard.monthlySales.map((item) => item.revenue), 1); return value ? Math.max(4, Math.min(100, (value / max) * 100)) : 0; }
  productSalesWidth(value: number, dashboard: DashboardData): number { const max = Math.max(...dashboard.productSales.map((item) => item.totalUnits), 1); return value ? Math.max(5, (value / max) * 100) : 0; }
}
