import { Component, computed, inject } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { map, tap } from 'rxjs';
import { LanguageService } from '../core/language.service';
import { TranslatePipe } from '../shared/translate.pipe';

const CONTENT: Record<string, { en: { title: string; eyebrow: string; body: string[] }; ar: { title: string; eyebrow: string; body: string[] } }> = {
  shipping: { en: { title: 'Shipping information', eyebrow: 'Delivery', body: ['Orders are prepared within one to two business days. Estimated delivery timing appears at checkout and may vary by destination.', 'When your order ships, it will appear in your account with its latest status. Orders over EGP 500 receive complimentary standard shipping.', 'Please review your address before placing the order. Contact support promptly if a correction is needed.'] }, ar: { title: 'معلومات الشحن', eyebrow: 'التوصيل', body: ['يتم تجهيز الطلبات خلال يوم إلى يومي عمل، ويظهر وقت التوصيل المتوقع أثناء إتمام الطلب وقد يختلف حسب الوجهة.', 'سيظهر تحديث الشحن في حسابك عند إرسال الطلب. تحصل الطلبات التي تتجاوز 500 جنيه مصري على شحن قياسي مجاني.', 'يرجى مراجعة العنوان قبل تأكيد الطلب والتواصل مع الدعم سريعاً عند الحاجة إلى تعديل.'] } },
  returns: { en: { title: 'Returns & exchanges', eyebrow: 'Straightforward support', body: ['Unused products in original condition can be returned within 30 days of delivery.', 'Contact support with your order number before returning an item. We will provide the return instructions and confirm eligibility.', 'Refunds are issued to the agreed payment method after the returned item has been inspected.'] }, ar: { title: 'الاسترجاع والاستبدال', eyebrow: 'دعم واضح', body: ['يمكن إرجاع المنتجات غير المستخدمة وبحالتهـا الأصلية خلال 30 يوماً من التوصيل.', 'تواصل مع الدعم برقم الطلب قبل إرسال المنتج لنزودك بالتعليمات ونؤكد الأهلية.', 'يتم رد المبلغ بطريقة الدفع المتفق عليها بعد فحص المنتج المرتجع.'] } },
  faq: { en: { title: 'Frequently asked questions', eyebrow: 'Help centre', body: ['How do I track an order? Sign in and open My Account to see every order and its current stage.', 'Can I change an order? Contact support as soon as possible. Changes are only possible before fulfillment begins.', 'Are product photos accurate? We use consistent studio photography, but screen settings can slightly affect color.'] }, ar: { title: 'الأسئلة الشائعة', eyebrow: 'مركز المساعدة', body: ['كيف أتتبع الطلب؟ سجل الدخول وافتح حسابي لمشاهدة جميع الطلبات وحالتها الحالية.', 'هل يمكن تعديل الطلب؟ تواصل مع الدعم سريعاً؛ التعديل متاح فقط قبل بدء التجهيز.', 'هل صور المنتجات دقيقة؟ نستخدم تصويراً متناسقاً، لكن إعدادات الشاشة قد تؤثر قليلاً على الألوان.'] } },
  contact: { en: { title: 'Contact us', eyebrow: 'We are here to help', body: ['Email support@vellora.store with your name and order number when relevant.', 'Support hours are Sunday–Thursday, 9:00–17:00 Cairo time. We aim to answer within one business day.', 'For security, our team will never ask for your password or full payment credentials.'] }, ar: { title: 'تواصل معنا', eyebrow: 'نحن هنا للمساعدة', body: ['راسل support@vellora.store مع اسمك ورقم الطلب عند الحاجة.', 'ساعات الدعم من الأحد إلى الخميس، من 9 صباحاً حتى 5 مساءً بتوقيت القاهرة، ونحاول الرد خلال يوم عمل.', 'لن يطلب فريقنا كلمة المرور أو بيانات الدفع الكاملة أبداً.'] } },
  privacy: { en: { title: 'Privacy policy', eyebrow: 'Your data', body: ['We collect the information needed to create your account, fulfill orders, provide support, and secure the service.', 'Passwords are hashed and authentication uses an HTTP-only session cookie. We do not sell personal information.', 'You may contact support to request access, correction, or deletion of your account data, subject to legal retention requirements.'] }, ar: { title: 'سياسة الخصوصية', eyebrow: 'بياناتك', body: ['نجمع البيانات اللازمة لإنشاء الحساب وتنفيذ الطلبات وتقديم الدعم وتأمين الخدمة.', 'يتم تشفير كلمات المرور وتستخدم المصادقة ملف جلسة HTTP-only. لا نبيع المعلومات الشخصية.', 'يمكنك التواصل مع الدعم لطلب الوصول إلى بيانات حسابك أو تصحيحها أو حذفها مع مراعاة متطلبات الاحتفاظ القانونية.'] } },
  terms: { en: { title: 'Terms of service', eyebrow: 'Using Vellora', body: ['By creating an account or placing an order, you agree to provide accurate information and use the service lawfully.', 'Product availability and prices may change. An order is accepted when it is confirmed by the service.', 'These terms are provided for the project release and should be reviewed by qualified local counsel before commercial launch.'] }, ar: { title: 'شروط الخدمة', eyebrow: 'استخدام Vellora', body: ['بإنشاء حساب أو تنفيذ طلب، توافق على تقديم معلومات صحيحة واستخدام الخدمة بصورة قانونية.', 'قد يتغير توفر المنتجات والأسعار، ويعتبر الطلب مقبولاً عند تأكيده من الخدمة.', 'هذه الشروط مقدمة لنسخة المشروع ويجب مراجعتها قانونياً قبل الإطلاق التجاري الفعلي.'] } },
};

@Component({ standalone: true, imports: [RouterLink, TranslatePipe], template: `<section class="info-page"><div class="container info-container"><div class="eyebrow">{{ page().eyebrow }}</div><h1>{{ page().title }}</h1>@for (paragraph of page().body; track paragraph) { <p>{{ paragraph }}</p> }<a class="btn btn-outline-ink mt-3" routerLink="/">{{ 'Back to Vellora' | translate }}</a></div></section>` })
export class InfoComponent {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly pageKey = toSignal(this.route.paramMap.pipe(
    map((params) => params.get('page') || 'faq'),
    tap((key) => { if (!CONTENT[key]) void this.router.navigateByUrl('/404', { replaceUrl: true }); }),
  ), { initialValue: this.route.snapshot.paramMap.get('page') || 'faq' });
  readonly page = computed(() => (CONTENT[this.pageKey()] || CONTENT['faq'])[this.language.language()]);
  constructor(public language: LanguageService) {}
}
