export interface LocationOption { en: string; ar: string }
export interface GovernorateOption extends LocationOption { cities: LocationOption[] }

const city = (en: string, ar: string): LocationOption => ({ en, ar });

// Egypt's 27 governorates with their principal cities and administrative centres.
// English values are stored in orders; labels switch with the application language.
export const EGYPT_LOCATIONS: GovernorateOption[] = [
  { en: 'Cairo', ar: 'القاهرة', cities: [city('Cairo', 'القاهرة'), city('New Cairo', 'القاهرة الجديدة'), city('Nasr City', 'مدينة نصر'), city('Heliopolis', 'مصر الجديدة'), city('Maadi', 'المعادي'), city('Helwan', 'حلوان'), city('Shorouk', 'الشروق'), city('Badr', 'بدر'), city('15th of May', '15 مايو'), city('Mokattam', 'المقطم')] },
  { en: 'Giza', ar: 'الجيزة', cities: [city('Giza', 'الجيزة'), city('6th of October', '6 أكتوبر'), city('Sheikh Zayed', 'الشيخ زايد'), city('Haram', 'الهرم'), city('Dokki', 'الدقي'), city('Mohandessin', 'المهندسين'), city('Imbaba', 'إمبابة'), city('Agouza', 'العجوزة'), city('Hawamdeya', 'الحوامدية'), city('Badrashein', 'البدرشين'), city('Saf', 'الصف'), city('Atfih', 'أطفيح'), city('Oseem', 'أوسيم'), city('Kerdasa', 'كرداسة')] },
  { en: 'Alexandria', ar: 'الإسكندرية', cities: [city('Alexandria', 'الإسكندرية'), city('Borg El Arab', 'برج العرب'), city('New Borg El Arab', 'برج العرب الجديدة')] },
  { en: 'Dakahlia', ar: 'الدقهلية', cities: [city('Mansoura', 'المنصورة'), city('Talkha', 'طلخا'), city('Mit Ghamr', 'ميت غمر'), city('Belqas', 'بلقاس'), city('Aga', 'أجا'), city('Sinbillawin', 'السنبلاوين'), city('Sherbin', 'شربين'), city('Manzala', 'المنزلة'), city('Dekernes', 'دكرنس'), city('Gamasa', 'جمصة'), city('Mataria', 'المطرية'), city('Minyet El Nasr', 'منية النصر'), city('Gammalia', 'الجمالية'), city('Bani Ebeid', 'بني عبيد'), city('Tami El Amdid', 'تمي الأمديد')] },
  { en: 'Red Sea', ar: 'البحر الأحمر', cities: [city('Hurghada', 'الغردقة'), city('Ras Ghareb', 'رأس غارب'), city('Safaga', 'سفاجا'), city('Quseir', 'القصير'), city('Marsa Alam', 'مرسى علم'), city('Shalateen', 'الشلاتين'), city('Halaib', 'حلايب')] },
  { en: 'Beheira', ar: 'البحيرة', cities: [city('Damanhour', 'دمنهور'), city('Kafr El Dawwar', 'كفر الدوار'), city('Rashid', 'رشيد'), city('Edko', 'إدكو'), city('Abu Hummus', 'أبو حمص'), city('Abu El Matamir', 'أبو المطامير'), city('Delengat', 'الدلنجات'), city('Mahmoudia', 'المحمودية'), city('Rahmaniya', 'الرحمانية'), city('Itay El Barud', 'إيتاي البارود'), city('Hosh Issa', 'حوش عيسى'), city('Kom Hamada', 'كوم حمادة'), city('Badr', 'بدر'), city('Wadi El Natrun', 'وادي النطرون'), city('Nubariya', 'النوبارية')] },
  { en: 'Fayoum', ar: 'الفيوم', cities: [city('Fayoum', 'الفيوم'), city('Itsa', 'إطسا'), city('Tamiya', 'طامية'), city('Sinnuris', 'سنورس'), city('Abshway', 'أبشواي'), city('Yusuf El Seddik', 'يوسف الصديق')] },
  { en: 'Gharbia', ar: 'الغربية', cities: [city('Tanta', 'طنطا'), city('Mahalla El Kubra', 'المحلة الكبرى'), city('Kafr El Zayat', 'كفر الزيات'), city('Zefta', 'زفتى'), city('Samanoud', 'سمنود'), city('Basyoun', 'بسيون'), city('Qutour', 'قطور'), city('Santa', 'السنطة')] },
  { en: 'Ismailia', ar: 'الإسماعيلية', cities: [city('Ismailia', 'الإسماعيلية'), city('Fayed', 'فايد'), city('Qantara East', 'القنطرة شرق'), city('Qantara West', 'القنطرة غرب'), city('Tell El Kebir', 'التل الكبير'), city('Abu Suwir', 'أبو صوير'), city('Qassasin', 'القصاصين')] },
  { en: 'Monufia', ar: 'المنوفية', cities: [city('Shibin El Kom', 'شبين الكوم'), city('Sadat City', 'مدينة السادات'), city('Menouf', 'منوف'), city('Ashmoun', 'أشمون'), city('Bagour', 'الباجور'), city('Quesna', 'قويسنا'), city('Berket El Sab', 'بركة السبع'), city('Tala', 'تلا'), city('Shohada', 'الشهداء'), city('Sers El Layan', 'سرس الليان')] },
  { en: 'Minya', ar: 'المنيا', cities: [city('Minya', 'المنيا'), city('New Minya', 'المنيا الجديدة'), city('Mallawi', 'ملوي'), city('Samalut', 'سمالوط'), city('Beni Mazar', 'بني مزار'), city('Maghagha', 'مغاغة'), city('Abu Qurqas', 'أبو قرقاص'), city('Matai', 'مطاي'), city('Deir Mawas', 'دير مواس'), city('Adwa', 'العدوة')] },
  { en: 'Qalyubia', ar: 'القليوبية', cities: [city('Benha', 'بنها'), city('Shubra El Kheima', 'شبرا الخيمة'), city('Qalyub', 'قليوب'), city('Khanka', 'الخانكة'), city('Qaha', 'قها'), city('Kafr Shukr', 'كفر شكر'), city('Toukh', 'طوخ'), city('Shebin El Qanater', 'شبين القناطر'), city('Obour', 'العبور'), city('Khosous', 'الخصوص')] },
  { en: 'New Valley', ar: 'الوادي الجديد', cities: [city('Kharga', 'الخارجة'), city('Dakhla', 'الداخلة'), city('Farafra', 'الفرافرة'), city('Baris', 'باريس'), city('Balat', 'بلاط')] },
  { en: 'Suez', ar: 'السويس', cities: [city('Suez', 'السويس')] },
  { en: 'Aswan', ar: 'أسوان', cities: [city('Aswan', 'أسوان'), city('New Aswan', 'أسوان الجديدة'), city('Edfu', 'إدفو'), city('Kom Ombo', 'كوم أمبو'), city('Daraw', 'دراو'), city('Nasr El Nuba', 'نصر النوبة'), city('Abu Simbel', 'أبو سمبل')] },
  { en: 'Assiut', ar: 'أسيوط', cities: [city('Assiut', 'أسيوط'), city('New Assiut', 'أسيوط الجديدة'), city('Dairut', 'ديروط'), city('Manfalut', 'منفلوط'), city('Qusiya', 'القوصية'), city('Abnoub', 'أبنوب'), city('Abu Tig', 'أبو تيج'), city('Ghanayem', 'الغنايم'), city('Sahel Selim', 'ساحل سليم'), city('Badari', 'البداري'), city('Sidfa', 'صدفا'), city('Fateh', 'الفتح')] },
  { en: 'Beni Suef', ar: 'بني سويف', cities: [city('Beni Suef', 'بني سويف'), city('New Beni Suef', 'بني سويف الجديدة'), city('Wasta', 'الواسطى'), city('Nasser', 'ناصر'), city('Ihnasia', 'إهناسيا'), city('Biba', 'ببا'), city('Samasta', 'سمسطا'), city('Fashn', 'الفشن')] },
  { en: 'Port Said', ar: 'بورسعيد', cities: [city('Port Said', 'بورسعيد'), city('Port Fouad', 'بورفؤاد')] },
  { en: 'Damietta', ar: 'دمياط', cities: [city('Damietta', 'دمياط'), city('New Damietta', 'دمياط الجديدة'), city('Ras El Bar', 'رأس البر'), city('Faraskour', 'فارسكور'), city('Kafr Saad', 'كفر سعد'), city('Zarqa', 'الزرقا'), city('Kafr El Battikh', 'كفر البطيخ'), city('Ezbet El Borg', 'عزبة البرج'), city('Mit Abou Ghaleb', 'ميت أبو غالب'), city('Roda', 'الروضة')] },
  { en: 'Sharkia', ar: 'الشرقية', cities: [city('Zagazig', 'الزقازيق'), city('10th of Ramadan', 'العاشر من رمضان'), city('Belbeis', 'بلبيس'), city('Minya El Qamh', 'منيا القمح'), city('Abu Hammad', 'أبو حماد'), city('Abu Kebir', 'أبو كبير'), city('Faqous', 'فاقوس'), city('Hihya', 'ههيا'), city('Kafr Saqr', 'كفر صقر'), city('Awlad Saqr', 'أولاد صقر'), city('Mashtoul El Souk', 'مشتول السوق'), city('Deyerb Negm', 'ديرب نجم'), city('El Husseiniya', 'الحسينية'), city('Qanayat', 'القنايات'), city('San El Hagar', 'صان الحجر'), city('Qareen', 'القرين'), city('Salheya El Gedida', 'الصالحية الجديدة'), city('Ibrahimiya', 'الإبراهيمية')] },
  { en: 'South Sinai', ar: 'جنوب سيناء', cities: [city('El Tor', 'الطور'), city('Sharm El Sheikh', 'شرم الشيخ'), city('Dahab', 'دهب'), city('Nuweiba', 'نويبع'), city('Taba', 'طابا'), city('Ras Sidr', 'رأس سدر'), city('Abu Zenima', 'أبو زنيمة'), city('Abu Redis', 'أبو رديس'), city('Saint Catherine', 'سانت كاترين')] },
  { en: 'Kafr El Sheikh', ar: 'كفر الشيخ', cities: [city('Kafr El Sheikh', 'كفر الشيخ'), city('Desouk', 'دسوق'), city('Fuwa', 'فوه'), city('Metoubes', 'مطوبس'), city('Baltim', 'بلطيم'), city('Burullus', 'البرلس'), city('Hamoul', 'الحامول'), city('Biyala', 'بيلا'), city('Riyadh', 'الرياض'), city('Sidi Salem', 'سيدي سالم'), city('Qallin', 'قلين')] },
  { en: 'Matrouh', ar: 'مطروح', cities: [city('Marsa Matrouh', 'مرسى مطروح'), city('El Alamein', 'العلمين'), city('New Alamein', 'العلمين الجديدة'), city('Dabaa', 'الضبعة'), city('Sallum', 'السلوم'), city('Siwa', 'سيوة'), city('Sidi Barrani', 'سيدي براني'), city('Hammam', 'الحمام'), city('Negila', 'النجيلة')] },
  { en: 'Luxor', ar: 'الأقصر', cities: [city('Luxor', 'الأقصر'), city('New Tiba', 'طيبة الجديدة'), city('Esna', 'إسنا'), city('Armant', 'أرمنت'), city('Qurna', 'القرنة'), city('Bayadiya', 'البياضية'), city('Tod', 'الطود'), city('Zinnia', 'الزينية')] },
  { en: 'Qena', ar: 'قنا', cities: [city('Qena', 'قنا'), city('New Qena', 'قنا الجديدة'), city('Nag Hammadi', 'نجع حمادي'), city('Deshna', 'دشنا'), city('Qus', 'قوص'), city('Naqada', 'نقادة'), city('Qift', 'قفط'), city('Abu Tesht', 'أبو تشت'), city('Farshut', 'فرشوط'), city('Waqf', 'الوقف')] },
  { en: 'North Sinai', ar: 'شمال سيناء', cities: [city('Arish', 'العريش'), city('Bir El Abd', 'بئر العبد'), city('Sheikh Zuweid', 'الشيخ زويد'), city('Rafah', 'رفح'), city('Hasana', 'الحسنة'), city('Nakhl', 'نخل')] },
  { en: 'Sohag', ar: 'سوهاج', cities: [city('Sohag', 'سوهاج'), city('New Sohag', 'سوهاج الجديدة'), city('Akhmim', 'أخميم'), city('Girga', 'جرجا'), city('Tahta', 'طهطا'), city('Tima', 'طما'), city('Maragha', 'المراغة'), city('Balyana', 'البلينا'), city('Dar El Salam', 'دار السلام'), city('Monsha', 'المنشأة'), city('Sakulta', 'ساقلتة'), city('Juhayna', 'جهينة'), city('Usayrat', 'العسيرات')] },
];
