import { Injectable, signal } from '@angular/core';

export type AppLanguage = 'en' | 'ar';

const ARABIC: Record<string, string> = {
  'Home': 'الرئيسية', 'Products': 'المنتجات', 'New arrivals': 'وصل حديثاً', 'Search studio catalog...': 'ابحث في كتالوج الاستوديو...',
  'Favorites': 'المفضلة', 'Sign in': 'تسجيل الدخول', 'Sign out': 'تسجيل الخروج', 'Admin portal': 'لوحة الإدارة', 'My account': 'حسابي',
  'Shop': 'المتجر', 'All products': 'كل المنتجات', 'Support': 'الدعم', 'Shipping info': 'معلومات الشحن', 'Returns': 'الاسترجاع', 'FAQ': 'الأسئلة الشائعة',
  'Contact us': 'تواصل معنا', 'Account': 'الحساب', 'Order tracking': 'تتبع الطلبات', 'Legal': 'قانوني', 'Privacy policy': 'سياسة الخصوصية',
  'Terms of service': 'شروط الخدمة', 'THE STUDIO EDIT': 'اختيارات الاستوديو', 'Curated objects · considered living': 'قطع مختارة · لحياة أكثر أناقة',
  'Studio quality.': 'جودة الاستوديو.', 'Everyday prices.': 'أسعار لكل يوم.',
  'Elevate your space with meticulously selected objects that balance useful design, lasting materials, and quiet beauty.': 'ارتقِ بمساحتك مع قطع مختارة بعناية تجمع بين التصميم العملي والخامات المتينة والجمال الهادئ.',
  'Explore collections': 'استكشف المجموعات', 'View new arrivals': 'شاهد الجديد', 'The edit': 'اختياراتنا', 'Featured products': 'منتجات مميزة',
  'Distinctive essentials chosen for quality, clarity, and long-term use.': 'أساسيات مميزة اخترناها للجودة والوضوح والاستخدام طويل الأمد.', 'View all': 'عرض الكل',
  'Home collection': 'مجموعة المنزل', 'Quiet forms for intentional rooms': 'أشكال هادئة لمساحات مدروسة', 'Shop the collection': 'تسوق المجموعة',
  'Studio essentials': 'أساسيات الاستوديو', 'Tools that disappear into the work': 'أدوات تنسجم مع عملك', 'Table & kitchen': 'المائدة والمطبخ', 'Made to gather around': 'صُممت لتجمعنا',
  'Why LuxeStudio': 'لماذا لوكس ستوديو', 'The studio advantage': 'ميزة الاستوديو', 'Intentional quality': 'جودة مقصودة', 'Fast delivery': 'توصيل سريع', '30-day returns': 'إرجاع خلال 30 يوماً',
  'Studio notes': 'رسائل الاستوديو', 'Objects, spaces, and new arrivals.': 'قطع ومساحات ووصولات جديدة.', 'Subscribe': 'اشترك', 'Email address': 'البريد الإلكتروني',
  'Studio catalog': 'كتالوج الاستوديو', 'Discover objects selected to bring clarity, character, and lasting usefulness to everyday spaces.': 'اكتشف قطعاً مختارة لتضيف الوضوح والشخصية والفائدة الدائمة لمساحتك اليومية.',
  'Categories': 'الفئات', 'Price range': 'نطاق السعر', 'Stock status': 'حالة المخزون', 'In stock only': 'المتوفر فقط', 'Search products': 'البحث عن منتجات',
  'Newest arrivals': 'الأحدث وصولاً', 'Price: low to high': 'السعر: من الأقل للأعلى', 'Price: high to low': 'السعر: من الأعلى للأقل', 'Top rated': 'الأعلى تقييماً', 'Name': 'الاسم',
  'No products found': 'لم يتم العثور على منتجات', 'Try another search or clear the current filters.': 'جرّب بحثاً آخر أو امسح عوامل التصفية.', 'Clear filters': 'مسح التصفية', 'Load more products': 'تحميل المزيد',
  'Add to cart': 'أضف إلى السلة', 'Out of stock': 'غير متوفر', 'in stock': 'متوفر', 'Product details': 'تفاصيل المنتج', 'Quantity': 'الكمية', 'Free shipping': 'شحن مجاني', 'Authentic': 'أصلي',
  'Secure checkout': 'دفع آمن', 'Your cart': 'سلة التسوق', 'Checkout details': 'بيانات إتمام الطلب', 'Shipping information': 'معلومات الشحن', 'Place order': 'إتمام الطلب',
  'Full name': 'الاسم الكامل', 'Phone number': 'رقم الهاتف', 'Street address': 'العنوان', 'City': 'المدينة', 'Subtotal': 'المجموع الفرعي', 'Shipping': 'الشحن', 'Total': 'الإجمالي',
  'Login': 'تسجيل الدخول', 'Register': 'إنشاء حساب', 'Password': 'كلمة المرور', 'First name': 'الاسم الأول', 'Last name': 'اسم العائلة', 'Create account': 'إنشاء الحساب',
  'Dashboard': 'لوحة التحكم', 'Orders': 'الطلبات', 'Customers': 'العملاء', 'View store': 'عرض المتجر', 'Admin Console': 'لوحة الإدارة', 'Dashboard overview': 'نظرة عامة',
  'Total revenue': 'إجمالي الإيرادات', 'Total orders': 'إجمالي الطلبات', 'Total products': 'إجمالي المنتجات', 'Low stock': 'مخزون منخفض', 'Recent orders': 'أحدث الطلبات',
  'Ordered': 'تم الطلب', 'Processing': 'قيد التجهيز', 'Shipped': 'تم الشحن', 'Delivered': 'تم التوصيل', 'Cancelled': 'ملغي',
  'Continue shopping': 'متابعة التسوق', 'Thank you for your order!': 'شكراً لطلبك!', 'My orders': 'طلباتي', 'Wishlist': 'قائمة المفضلة',
  'Lost in the collection': 'تائه في المجموعة', 'This outfit does not live here.': 'هذه الإطلالة ليست هنا.',
  'The page may have moved, sold out, or taken an unexpected trip to the fitting room.': 'ربما انتقلت الصفحة أو نفدت أو ذهبت في رحلة غير متوقعة إلى غرفة القياس.',
  'Return home': 'العودة للرئيسية', 'Browse the collection': 'تصفح المجموعة', 'Returning to the landing page in': 'العودة تلقائياً إلى الصفحة الرئيسية خلال',
  'Objects selected': 'قطع مختارة',
  'for modern rituals': 'لطقوس عصرية',
  'Edition 01': 'الإصدار 01',
  'Thoughtful selection and dependable service, from first click to daily use.': 'اختيارات مدروسة وخدمة موثوقة من أول نقرة وحتى الاستخدام اليومي.',
  'Every object is reviewed for materials, finish, function, and lasting appeal.': 'نراجع كل قطعة من حيث الخامات والتشطيب والوظيفة والجمال الدائم.',
  'Clear stock visibility, prompt fulfillment, and tracking throughout the journey.': 'مخزون واضح وتجهيز سريع وتتبع للطلب طوال الرحلة.',
  'A straightforward return window and responsive support if something is not right.': 'فترة إرجاع واضحة ودعم سريع إذا لم يكن كل شيء كما ينبغي.',
  'Join our monthly edit. No noise, just considered inspiration.': 'انضم إلى مختاراتنا الشهرية؛ بلا ضوضاء، فقط إلهام مدروس.',
  'Elevating everyday commerce through intentional design, carefully selected products, and reliable service.': 'نرتقي بتجربة التسوق اليومية عبر تصميم هادف ومنتجات مختارة بعناية وخدمة موثوقة.',
  'All rights reserved.': 'جميع الحقوق محفوظة.',
  'Welcome back. Enter your details to continue.': 'مرحباً بعودتك. أدخل بياناتك للمتابعة.',
  'Enter a valid email address.': 'أدخل بريداً إلكترونياً صالحاً.',
  'Need help?': 'تحتاج مساعدة؟',
  'Toggle password visibility': 'إظهار أو إخفاء كلمة المرور',
  'Password is required.': 'كلمة المرور مطلوبة.',
  'or': 'أو',
  'New to LuxeStudio?': 'جديد في لوكس ستوديو؟',
  'Save favorites, checkout faster, and follow every order.': 'احفظ مفضلاتك وأكمل الشراء أسرع وتابع كل طلب.',
  'I agree to the': 'أوافق على',
  'terms': 'الشروط',
  'and': 'و',
  'privacy policy': 'سياسة الخصوصية',
  'Already have an account?': 'لديك حساب بالفعل؟',
  'Your cart is empty': 'سلة التسوق فارغة',
  'Explore the catalog and add something considered.': 'استكشف الكتالوج وأضف قطعة مختارة.',
  'Cash on delivery': 'الدفع عند الاستلام',
  'Pay safely when your order arrives.': 'ادفع بأمان عند وصول طلبك.',
  'Your order is confirmed. You can follow its progress from your account.': 'تم تأكيد طلبك ويمكنك متابعة تقدمه من حسابك.',
  'Order number': 'رقم الطلب',
  'Date': 'التاريخ',
  'Order status': 'حالة الطلب',
  'Saved collection': 'المجموعة المحفوظة',
  'Everything that caught your eye, kept in one considered place.': 'كل ما لفت انتباهك محفوظ في مكان واحد منظم.',
  'Your favorites are empty': 'قائمة المفضلة فارغة',
  'Save products from the catalog to find them here.': 'احفظ المنتجات من الكتالوج لتجدها هنا.',
  'Showing': 'عرض',
  'of': 'من',
  'products': 'منتجاً',
  'Loading…': 'جارٍ التحميل…',
  'Sort products': 'ترتيب المنتجات',
  'Personal studio': 'مساحتك الشخصية',
  'Manage your details, favorites, and every order in one place.': 'أدر بياناتك ومفضلاتك وجميع طلباتك من مكان واحد.',
  'Profile': 'الملف الشخصي',
  'Security': 'الأمان',
  'orders': 'طلبات',
  'No orders yet': 'لا توجد طلبات بعد',
  'Your placed orders will appear here.': 'ستظهر طلباتك المكتملة هنا.',
  'Order': 'الطلب',
  'Track order': 'تتبع الطلب',
  'Profile details': 'بيانات الملف الشخصي',
  'Keep your delivery information current.': 'حافظ على تحديث بيانات التوصيل.',
  'Email changes require support verification.': 'تغيير البريد الإلكتروني يتطلب تحقق فريق الدعم.',
  'Save changes': 'حفظ التغييرات',
  'Use a unique password you do not use elsewhere.': 'استخدم كلمة مرور فريدة لا تستخدمها في مكان آخر.',
  'Current password': 'كلمة المرور الحالية',
  'New password': 'كلمة المرور الجديدة',
  '10+ characters with uppercase, lowercase, number, and symbol.': '10 أحرف أو أكثر تتضمن حروفاً كبيرة وصغيرة ورقماً ورمزاً.',
  'Change password': 'تغيير كلمة المرور',
  'Studio imagery': 'صور الاستوديو',
  'Ships within 1–2 business days': 'يُشحن خلال يوم إلى يومي عمل',
  'Join the restock list': 'انضم إلى قائمة إعادة التوفر',
  'Decrease quantity': 'تقليل الكمية',
  'Increase quantity': 'زيادة الكمية',
  'Adding...': 'جارٍ الإضافة...',
  'Favorite': 'المفضلة',
  'Materials & care': 'الخامات والعناية',
  'Made with carefully sourced materials. Wipe clean with a soft, dry cloth and avoid abrasive cleaners.': 'مصنوع من خامات مختارة بعناية. يُنظف بقطعة قماش ناعمة وجافة مع تجنب المنظفات الكاشطة.',
  'Delivery & returns': 'التوصيل والإرجاع',
  'Tracked delivery and a 30-day return window on unused products in original packaging.': 'توصيل قابل للتتبع وإرجاع خلال 30 يوماً للمنتجات غير المستخدمة وفي عبوتها الأصلية.',
  'Complete the look': 'أكمل الإطلالة',
  'You may also like': 'قد يعجبك أيضاً',
  'Back to LuxeStudio': 'العودة إلى لوكس ستوديو',
  'Administrator': 'مدير النظام',
  'Here is what is happening across LuxeStudio today.': 'إليك ما يحدث في لوكس ستوديو اليوم.',
  'Add product': 'إضافة منتج',
  'Confirmed orders': 'الطلبات المؤكدة',
  'Across all statuses': 'عبر جميع الحالات',
  'Registered accounts': 'الحسابات المسجلة',
  'Active catalog': 'الكتالوج النشط',
  'Needs attention': 'يحتاج إلى متابعة',
  'Status': 'الحالة',
  'Latest products': 'أحدث المنتجات',
  'Manage catalog': 'إدارة الكتالوج',
  'Stock': 'المخزون',
  'remaining': 'متبقي',
  'All stock levels look healthy.': 'كل مستويات المخزون جيدة.',
  'Review fulfillment, update statuses, and monitor customer deliveries.': 'راجع التنفيذ وحدّث الحالات وتابع توصيلات العملاء.',
  'All statuses': 'كل الحالات',
  'Items': 'العناصر',
  'No orders match this status.': 'لا توجد طلبات مطابقة لهذه الحالة.',
  'View registered customer accounts and contact details.': 'اعرض حسابات العملاء المسجلة وبيانات التواصل.',
  'Search customers': 'البحث عن العملاء',
  'accounts': 'حسابات',
  'Customer': 'العميل',
  'Email': 'البريد الإلكتروني',
  'Phone': 'الهاتف',
  'Role': 'الصلاحية',
  'Joined': 'تاريخ الانضمام',
  'No customers found.': 'لم يتم العثور على عملاء.',
  'Create, edit, price, and manage catalog availability.': 'أنشئ المنتجات وعدّلها وحدد أسعارها وأدر توفر الكتالوج.',
  'Search catalog': 'البحث في الكتالوج',
  'Product': 'المنتج',
  'Category': 'الفئة',
  'Price': 'السعر',
  'Featured': 'مميز',
  'Actions': 'الإجراءات',
  'Edit': 'تعديل',
  'Delete': 'حذف',
  'Catalog editor': 'محرر الكتالوج',
  'Edit product': 'تعديل المنتج',
  'New product': 'منتج جديد',
  'Description': 'الوصف',
  'Collection': 'المجموعة',
  'Old price': 'السعر السابق',
  'Image path or HTTPS URL': 'مسار الصورة أو رابط HTTPS',
  'Use /assets/... for bundled images.': 'استخدم ‎/assets/...‎ للصور المرفقة.',
  'New arrival': 'وصل حديثاً',
  'Saving...': 'جارٍ الحفظ...',
  'Save product': 'حفظ المنتج',
  'Cancel': 'إلغاء',
  'Secure, encrypted session': 'جلسة آمنة ومشفرة',
  'optional': 'اختياري',
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly language = signal<AppLanguage>((localStorage.getItem('luxestudio-language') as AppLanguage) || 'en');
  constructor() { this.apply(this.language()); }
  translate(value: string): string { return this.language() === 'ar' ? (ARABIC[value] || value) : value; }
  toggle(): void { this.set(this.language() === 'en' ? 'ar' : 'en'); }
  set(language: AppLanguage): void { this.language.set(language); localStorage.setItem('luxestudio-language', language); this.apply(language); }
  private apply(language: AppLanguage): void { document.documentElement.lang = language; document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'; document.body.classList.toggle('rtl', language === 'ar'); }
}
