import { Injectable, signal } from '@angular/core';

export type AppLanguage = 'en' | 'ar';

const ARABIC: Record<string, string> = {
  'Home': 'الرئيسية', 'Products': 'المنتجات', 'New arrivals': 'وصل حديثاً', 'Search studio catalog...': 'ابحث في كتالوج الاستوديو...', 'Search products...': 'ابحث عن المنتجات...',
  'Favorites': 'المفضلة', 'Sign in': 'تسجيل الدخول', 'Sign out': 'تسجيل الخروج', 'Admin portal': 'لوحة الإدارة', 'My account': 'حسابي',
  'Shop': 'المتجر', 'All products': 'كل المنتجات', 'Support': 'الدعم', 'Shipping info': 'معلومات الشحن', 'Returns': 'الاسترجاع', 'FAQ': 'الأسئلة الشائعة',
  'Contact us': 'تواصل معنا', 'Account': 'الحساب', 'Order tracking': 'تتبع الطلبات', 'Legal': 'قانوني', 'Privacy policy': 'سياسة الخصوصية',
  'Terms of service': 'شروط الخدمة', 'THE STUDIO EDIT': 'اختيارات الاستوديو', 'Curated objects · considered living': 'قطع مختارة · لحياة أكثر أناقة',
  'Studio quality.': 'جودة الاستوديو.', 'Everyday prices.': 'أسعار لكل يوم.',
  'Elevate your space with meticulously selected objects that balance useful design, lasting materials, and quiet beauty.': 'ارتقِ بمساحتك مع قطع مختارة بعناية تجمع بين التصميم العملي والخامات المتينة والجمال الهادئ.',
  'Explore collections': 'استكشف المجموعات', 'View new arrivals': 'شاهد الجديد', 'The edit': 'اختياراتنا', 'Featured products': 'منتجات مميزة',
  'Distinctive essentials chosen for quality, clarity, and long-term use.': 'أساسيات مميزة اخترناها للجودة والوضوح والاستخدام طويل الأمد.', 'View all': 'عرض الكل',
  'Home collection': 'مجموعة المنزل', 'Quiet forms for intentional rooms': 'أشكال هادئة لمساحات مدروسة', 'Shop the collection': 'تسوق المجموعة',
  'Studio essentials': 'أساسيات الاستوديو', 'Tools that disappear into the work': 'أدوات تنسجم مع عملك', 'Table & kitchen': 'المائدة والمطبخ', 'Made to gather around': 'صُممت لتجمعنا',
  'The studio advantage': 'ميزة الاستوديو', 'Intentional quality': 'جودة مقصودة', 'Fast delivery': 'توصيل سريع', '30-day returns': 'إرجاع خلال 30 يوماً',
  'Studio notes': 'رسائل الاستوديو', 'Objects, spaces, and new arrivals.': 'قطع ومساحات ووصولات جديدة.', 'Subscribe': 'اشترك', 'Email address': 'البريد الإلكتروني',
  'Studio catalog': 'كتالوج الاستوديو', 'Discover objects selected to bring clarity, character, and lasting usefulness to everyday spaces.': 'اكتشف قطعاً مختارة لتضيف الوضوح والشخصية والفائدة الدائمة لمساحتك اليومية.', 'Browse the complete collection and filter by category, availability, or price.': 'تصفح المجموعة الكاملة وصفِّها حسب الفئة أو التوفر أو السعر.',
  'Categories': 'الفئات', 'Price range': 'نطاق السعر', 'Stock status': 'حالة المخزون', 'In stock only': 'المتوفر فقط', 'Search products': 'البحث عن منتجات',
  'Newest arrivals': 'الأحدث وصولاً', 'Price: low to high': 'السعر: من الأقل للأعلى', 'Price: high to low': 'السعر: من الأعلى للأقل', 'Name': 'الاسم',
  'No products found': 'لم يتم العثور على منتجات', 'Try another search or clear the current filters.': 'جرّب بحثاً آخر أو امسح عوامل التصفية.', 'Clear filters': 'مسح التصفية', 'Load more products': 'تحميل المزيد',
  'Add to cart': 'أضف إلى السلة', 'Out of stock': 'غير متوفر', 'in stock': 'متوفر', 'Product details': 'تفاصيل المنتج', 'Quantity': 'الكمية', 'Free shipping': 'شحن مجاني', 'Authentic': 'أصلي',
  'Secure checkout': 'دفع آمن', 'Your cart': 'سلة التسوق', 'Checkout details': 'بيانات إتمام الطلب', 'Shipping information': 'معلومات الشحن', 'Place order': 'إتمام الطلب',
  'Full name': 'الاسم الكامل', 'Phone number': 'رقم الهاتف', 'Street address': 'العنوان', 'City': 'المدينة', 'Subtotal': 'المجموع الفرعي', 'Shipping': 'الشحن', 'Total': 'الإجمالي',
  'Login': 'تسجيل الدخول', 'Register': 'إنشاء حساب', 'Password': 'كلمة المرور', 'First name': 'الاسم الأول', 'Last name': 'اسم العائلة', 'Create account': 'إنشاء الحساب',
  'Dashboard': 'لوحة التحكم', 'Orders': 'الطلبات', 'Customers': 'العملاء', 'View store': 'عرض المتجر', 'Admin Console': 'لوحة الإدارة', 'Dashboard overview': 'نظرة عامة',
  'Total revenue': 'إجمالي الإيرادات', 'Total orders': 'إجمالي الطلبات', 'Total products': 'إجمالي المنتجات', 'Low stock': 'مخزون منخفض', 'Recent orders': 'أحدث الطلبات',
  'Ordered': 'تم الطلب', 'Processing': 'قيد التجهيز', 'Shipped': 'تم الشحن', 'Delivered': 'تم التوصيل', 'Cancelled': 'ملغي',
  'Continue shopping': 'متابعة التسوق', 'Thank you for your order!': 'شكراً لطلبك!', 'My orders': 'طلباتي', 'Wishlist': 'قائمة المفضلة',
  'Lost in the collection': 'تائه في المجموعة', 'This outfit does not live here.': 'هذه الإطلالة ليست هنا.',
  'The page may have moved, sold out, or taken an unexpected trip to the fitting room.': 'ربما انتقلت الصفحة أو نفدت أو ذهبت في رحلة غير متوقعة إلى غرفة القياس.',
  'Return home': 'العودة للرئيسية', 'Browse the collection': 'تصفح المجموعة', 'Returning to the landing page in': 'العودة تلقائياً إلى الصفحة الرئيسية خلال',
  'Objects selected': 'قطع مختارة',
  'for modern rituals': 'لطقوس عصرية',
  'Edition 01': 'الإصدار 01',
  'Thoughtful selection and dependable service, from first click to daily use.': 'اختيارات مدروسة وخدمة موثوقة من أول نقرة وحتى الاستخدام اليومي.',
  'Every object is reviewed for materials, finish, function, and lasting appeal.': 'نراجع كل قطعة من حيث الخامات والتشطيب والوظيفة والجمال الدائم.',
  'Clear stock visibility, prompt fulfillment, and tracking throughout the journey.': 'مخزون واضح وتجهيز سريع وتتبع للطلب طوال الرحلة.',
  'A straightforward return window and responsive support if something is not right.': 'فترة إرجاع واضحة ودعم سريع إذا لم يكن كل شيء كما ينبغي.',
  'Join our monthly edit. No noise, just considered inspiration.': 'انضم إلى مختاراتنا الشهرية؛ بلا ضوضاء، فقط إلهام مدروس.',
  'Elevating everyday commerce through intentional design, carefully selected products, and reliable service.': 'نرتقي بتجربة التسوق اليومية عبر تصميم هادف ومنتجات مختارة بعناية وخدمة موثوقة.',
  'All rights reserved.': 'جميع الحقوق محفوظة.',
  'Welcome back. Enter your details to continue.': 'مرحباً بعودتك. أدخل بياناتك للمتابعة.',
  'Enter a valid email address.': 'أدخل بريداً إلكترونياً صالحاً.',
  'Need help?': 'تحتاج مساعدة؟',
  'Toggle password visibility': 'إظهار أو إخفاء كلمة المرور',
  'Password is required.': 'كلمة المرور مطلوبة.',
  'or': 'أو',
  'Save favorites, checkout faster, and follow every order.': 'احفظ مفضلاتك وأكمل الشراء أسرع وتابع كل طلب.',
  'I agree to the': 'أوافق على',
  'terms': 'الشروط',
  'and': 'و',
  'privacy policy': 'سياسة الخصوصية',
  'Already have an account?': 'لديك حساب بالفعل؟',
  'Your cart is empty': 'سلة التسوق فارغة',
  'Explore the catalog and add something considered.': 'استكشف الكتالوج وأضف قطعة مختارة.',
  'Cash on delivery': 'الدفع عند الاستلام',
  'Pay safely when your order arrives.': 'ادفع بأمان عند وصول طلبك.',
  'Your order is confirmed. You can follow its progress from your account.': 'تم تأكيد طلبك ويمكنك متابعة تقدمه من حسابك.',
  'Order number': 'رقم الطلب',
  'Date': 'التاريخ',
  'Order status': 'حالة الطلب',
  'Saved collection': 'المجموعة المحفوظة',
  'Everything that caught your eye, kept in one considered place.': 'كل ما لفت انتباهك محفوظ في مكان واحد منظم.',
  'Your favorites are empty': 'قائمة المفضلة فارغة',
  'Save products from the catalog to find them here.': 'احفظ المنتجات من الكتالوج لتجدها هنا.',
  'Showing': 'عرض',
  'of': 'من',
  'products': 'منتجاً',
  'Loading…': 'جارٍ التحميل…',
  'Sort products': 'ترتيب المنتجات',
  'Personal studio': 'مساحتك الشخصية', 'Your account': 'حسابك',
  'Manage your details, favorites, and every order in one place.': 'أدر بياناتك ومفضلاتك وجميع طلباتك من مكان واحد.',
  'Profile': 'الملف الشخصي',
  'Security': 'الأمان',
  'orders': 'طلبات',
  'No orders yet': 'لا توجد طلبات بعد',
  'Your placed orders will appear here.': 'ستظهر طلباتك المكتملة هنا.',
  'Order': 'الطلب',
  'Track order': 'تتبع الطلب',
  'Profile details': 'بيانات الملف الشخصي',
  'Keep your delivery information current.': 'حافظ على تحديث بيانات التوصيل.',
  'Email changes require support verification.': 'تغيير البريد الإلكتروني يتطلب تحقق فريق الدعم.',
  'Save changes': 'حفظ التغييرات',
  'Use a unique password you do not use elsewhere.': 'استخدم كلمة مرور فريدة لا تستخدمها في مكان آخر.',
  'Current password': 'كلمة المرور الحالية',
  'New password': 'كلمة المرور الجديدة',
  '10+ characters with uppercase, lowercase, number, and symbol.': '10 أحرف أو أكثر تتضمن حروفاً كبيرة وصغيرة ورقماً ورمزاً.',
  'Change password': 'تغيير كلمة المرور',
  'Studio imagery': 'صور الاستوديو',
  'Ships within 1–2 business days': 'يُشحن خلال يوم إلى يومي عمل',
  'Join the restock list': 'انضم إلى قائمة إعادة التوفر',
  'Decrease quantity': 'تقليل الكمية',
  'Increase quantity': 'زيادة الكمية',
  'Adding...': 'جارٍ الإضافة...',
  'Favorite': 'المفضلة',
  'Materials & care': 'الخامات والعناية',
  'Made with carefully sourced materials. Wipe clean with a soft, dry cloth and avoid abrasive cleaners.': 'مصنوع من خامات مختارة بعناية. يُنظف بقطعة قماش ناعمة وجافة مع تجنب المنظفات الكاشطة.',
  'Delivery & returns': 'التوصيل والإرجاع',
  'Tracked delivery and a 30-day return window on unused products in original packaging.': 'توصيل قابل للتتبع وإرجاع خلال 30 يوماً للمنتجات غير المستخدمة وفي عبوتها الأصلية.',
  'Complete the look': 'أكمل الإطلالة',
  'You may also like': 'قد يعجبك أيضاً',
  'Administrator': 'مدير النظام',
  'Add product': 'إضافة منتج',
  'Confirmed orders': 'الطلبات المؤكدة',
  'Across all statuses': 'عبر جميع الحالات',
  'Registered accounts': 'الحسابات المسجلة',
  'Active catalog': 'الكتالوج النشط',
  'Needs attention': 'يحتاج إلى متابعة',
  'Status': 'الحالة',
  'Latest products': 'أحدث المنتجات',
  'Manage catalog': 'إدارة الكتالوج',
  'Stock': 'المخزون',
  'remaining': 'متبقي',
  'All stock levels look healthy.': 'كل مستويات المخزون جيدة.',
  'Review fulfillment, update statuses, and monitor customer deliveries.': 'راجع التنفيذ وحدّث الحالات وتابع توصيلات العملاء.',
  'All statuses': 'كل الحالات',
  'Items': 'العناصر',
  'No orders match this status.': 'لا توجد طلبات مطابقة لهذه الحالة.',
  'View registered customer accounts and contact details.': 'اعرض حسابات العملاء المسجلة وبيانات التواصل.',
  'Search customers': 'البحث عن العملاء',
  'accounts': 'حسابات',
  'Customer': 'العميل',
  'Email': 'البريد الإلكتروني',
  'Phone': 'الهاتف',
  'Role': 'الصلاحية',
  'Joined': 'تاريخ الانضمام',
  'No customers found.': 'لم يتم العثور على عملاء.',
  'Create, edit, price, and manage catalog availability.': 'أنشئ المنتجات وعدّلها وحدد أسعارها وأدر توفر الكتالوج.',
  'Search catalog': 'البحث في الكتالوج',
  'Product': 'المنتج',
  'Category': 'الفئة',
  'Price': 'السعر',
  'Featured': 'مميز',
  'Actions': 'الإجراءات',
  'Edit': 'تعديل',
  'Delete': 'حذف',
  'Catalog editor': 'محرر الكتالوج',
  'Edit product': 'تعديل المنتج',
  'New product': 'منتج جديد',
  'Description': 'الوصف',
  'Collection': 'المجموعة',
  'Old price': 'السعر السابق',
  'Image path or HTTPS URL': 'مسار الصورة أو رابط HTTPS',
  'Use /assets/... for bundled images.': 'استخدم ‎/assets/...‎ للصور المرفقة.',
  'New arrival': 'وصل حديثاً',
  'Saving...': 'جارٍ الحفظ...',
  'Save product': 'حفظ المنتج',
  'Cancel': 'إلغاء',
  'Secure, encrypted session': 'جلسة آمنة ومشفرة',
  'optional': 'اختياري',
  'Enable dark mode': 'تفعيل الوضع الداكن',
  'Enable light mode': 'تفعيل الوضع الفاتح',
  'Filters': 'عوامل التصفية',
  'active': 'نشط',
  'Clear': 'مسح',
  'Collections': 'المجموعات',
  'All collections': 'كل المجموعات',
  'Min': 'الأدنى',
  'Max': 'الأقصى',
  'Availability': 'التوفر',
  'New arrivals only': 'الوصولات الجديدة فقط',
  'Featured only': 'المميزة فقط',
  'Apply filters': 'تطبيق التصفية',
  'of this product in your cart': 'من هذا المنتج في سلتك',
  'View cart': 'عرض السلة',
  'Remove item': 'إزالة المنتج',
  'Currently unavailable — remove or reduce this item': 'غير متوفر حالياً — احذف المنتج أو قلل الكمية',
  'Full name is required': 'الاسم الكامل مطلوب',
  'Enter a valid phone number': 'أدخل رقم هاتف صالحاً',
  'Street address is required': 'عنوان الشارع مطلوب',
  'Building, street, area': 'المبنى والشارع والمنطقة',
  'Governorate': 'المحافظة',
  'Select governorate': 'اختر المحافظة',
  'Governorate is required': 'المحافظة مطلوبة',
  'Select city': 'اختر المدينة',
  'City is required': 'المدينة مطلوبة',
  'Tip: open a list and type the first letters to jump to a location.': 'نصيحة: افتح القائمة واكتب أول الحروف للوصول إلى المكان سريعاً.',
  'Free': 'مجاني',
  'Resolve unavailable cart items before placing the order.': 'عالج المنتجات غير المتوفرة في السلة قبل تأكيد الطلب.',
  'Cost': 'التكلفة',
  'Manual override': 'إيقاف يدوي',
  'Enter at least 2 characters': 'أدخل حرفين على الأقل',
  'minimum 20 characters': '20 حرفاً على الأقل',
  'Choose an existing category or enter a new one.': 'اختر فئة موجودة أو أدخل فئة جديدة.',
  'Selling price': 'سعر البيع',
  'Mark out of stock': 'تحديد كغير متوفر',
  'Hide purchasing even when physical stock remains.': 'إيقاف الشراء حتى مع وجود مخزون فعلي.',
  'View customer details': 'عرض بيانات العميل',
  'Order details': 'تفاصيل الطلب',
  'Close': 'إغلاق',
  'Placed': 'تاريخ الطلب',
  'Customer account': 'حساب العميل',
  'Account phone': 'هاتف الحساب',
  'Delivery contact': 'بيانات التوصيل',
  'Delivery phone': 'هاتف التوصيل',
  'Purchased products': 'المنتجات المشتراة',
  'items': 'منتجات',
  'Sales dashboard': 'لوحة المبيعات',
  'Average order value': 'متوسط قيمة الطلب',
  'units sold': 'وحدة مباعة',
  'Unavailable products': 'منتجات غير متوفرة',
  'need attention': 'تحتاج متابعة',
  'Delivered revenue': 'إيرادات الطلبات المسلمة',
  'Cancelled value': 'قيمة الطلبات الملغاة',
  'Inventory retail value': 'قيمة المخزون بسعر البيع',
  'units': 'وحدة',
  'Revenue': 'الإيرادات',
  'Sales will appear after the first order.': 'ستظهر المبيعات بعد أول طلب.',
  'Order status mix': 'توزيع حالات الطلبات',
  'Stock alerts': 'تنبيهات المخزون',
  'units on hand': 'وحدة بالمخزون',
  'Why Vellora': 'لماذا Vellora',
  'New to Vellora?': 'جديد في Vellora؟',
  'Back to Vellora': 'العودة إلى Vellora',
  'Wear Your Confidence': 'ارتدِ ثقتك',
  'Own the moment': 'امتلك اللحظة',
  'Move without permission': 'تحرك بلا قيود',
  'Made to be remembered': 'صُمم ليبقى في الذاكرة',
  'Previous look': 'الإطلالة السابقة',
  'Next look': 'الإطلالة التالية',
  'Shop collection': 'تسوق المجموعة',
  'Scroll': 'مرر للأسفل',
  'Explore the collection': 'استكشف المجموعة',
  'Accessories': 'الإكسسوارات',
  'Interface': 'واجهة الاستخدام',
  'Store sales & debts': 'مبيعات المحل والديون',
  'Record counter sales, track customer balances, and add dated payments.': 'سجل مبيعات المحل وتابع أرصدة العملاء وأضف الدفعات بتاريخها.',
  'Record store sale': 'تسجيل بيع من المحل',
  'Store revenue': 'إيرادات المحل',
  'sales': 'مبيعات',
  'Collected': 'المحصل',
  'Paid across all methods': 'المدفوع بجميع طرق الدفع',
  'Outstanding debt': 'الديون المستحقة',
  'customers with debt': 'عملاء عليهم ديون',
  'Collection rate': 'نسبة التحصيل',
  'Of recorded store revenue': 'من إيرادات المحل المسجلة',
  'Highest customer debts': 'أعلى ديون العملاء',
  'Balances are grouped by customer name and phone.': 'يتم تجميع الأرصدة حسب اسم العميل ورقم الهاتف.',
  'No phone': 'بدون هاتف',
  'No outstanding customer debt.': 'لا توجد ديون مستحقة على العملاء.',
  'Customer debt accounts': 'حسابات ديون العملاء',
  'Open a sale below to record a payment.': 'افتح عملية بيع أدناه لتسجيل دفعة.',
  'Sales': 'المبيعات',
  'Paid': 'المدفوع',
  'Debt': 'الدين',
  'Last date': 'آخر تاريخ',
  'No debts to display.': 'لا توجد ديون للعرض.',
  'Store sales ledger': 'سجل مبيعات المحل',
  'Every sale and payment keeps its original date and method.': 'يحتفظ كل بيع ودفعة بالتاريخ وطريقة الدفع.',
  'Sale date': 'تاريخ البيع',
  'Action': 'الإجراء',
  'Manage debt': 'إدارة الدين',
  'View payments': 'عرض الدفعات',
  'No store sales recorded yet.': 'لم يتم تسجيل مبيعات من المحل بعد.',
  'Store counter': 'كاشير المحل',
  'Customer name': 'اسم العميل',
  'Choose product': 'اختر منتجًا',
  'Unit price': 'سعر الوحدة',
  'Amount paid now': 'المبلغ المدفوع الآن',
  'Leave 0 to record the full amount as debt.': 'اتركه 0 لتسجيل كامل المبلغ كدين.',
  'Payment method': 'طريقة الدفع',
  'Note': 'ملاحظة',
  'Sale total': 'إجمالي البيع',
  'Remaining debt': 'الدين المتبقي',
  'Record sale': 'تسجيل البيع',
  'Customer debt': 'دين العميل',
  'Payment history': 'سجل الدفعات',
  'No payments recorded.': 'لم يتم تسجيل دفعات.',
  'Add payment': 'إضافة دفعة',
  'Payment amount': 'مبلغ الدفعة',
  'Payment date': 'تاريخ الدفعة',
  'Record payment': 'تسجيل الدفعة',
  'Partially paid': 'مدفوع جزئيًا',
  'Cash': 'نقدي',
  'Card': 'بطاقة',
  'Bank transfer': 'تحويل بنكي',
  'Mobile wallet': 'محفظة إلكترونية',
  'Other': 'أخرى',
  'Online and store revenue, customer debts, orders, and inventory in one view.': 'إيرادات الموقع والمحل وديون العملاء والطلبات والمخزون في شاشة واحدة.',
  'Online revenue': 'إيرادات الموقع',
  'counter sales': 'مبيعات مباشرة',
  'debt accounts': 'حسابات ديون',
  'Store payments collected': 'دفعات المحل المحصلة',
  'Average sale value': 'متوسط قيمة البيع',
  'Units sold': 'الوحدات المباعة',
  'Delivered online revenue': 'إيرادات الطلبات المسلمة',
  'Six-month revenue': 'إيرادات ستة أشهر',
  'Online and in-store sales by month.': 'مبيعات الموقع والمحل حسب الشهر.',
  'Online': 'الموقع',
  'In store': 'المحل',
  'Sales will appear after the first transaction.': 'ستظهر المبيعات بعد أول عملية.',
  'Balances that need collection.': 'الأرصدة التي تحتاج إلى تحصيل.',
  'View ledger': 'عرض السجل',
  'Homepage editor': 'محرر الصفحة الرئيسية',
  'Choose the campaign images yourself without changing code.': 'اختر صور الحملة بنفسك دون تعديل الكود.',
  'Publish homepage': 'نشر الصفحة الرئيسية',
  'No-code controls': 'تحكم بدون كود',
  'Keep the campaign current.': 'حافظ على تجدد الحملة.',
  'The current editorial art stays live by default. Choose catalog products or upload optimized images only when you want a change.': 'تبقى الصور الحالية منشورة افتراضياً. اختر منتجات من الكتالوج أو ارفع صوراً محسّنة عندما تريد التغيير.',
  'Animated hero images': 'صور الواجهة المتحركة',
  'Controls the three images in the opening carousel.': 'تتحكم في الصور الثلاث داخل عارض البداية.',
  'Editorial landing panels': 'لوحات صور صفحة الهبوط',
  'Controls the two large images below featured products.': 'تتحكم في الصورتين الكبيرتين أسفل المنتجات المميزة.',
  'slots': 'خانات',
  'Vellora campaign': 'حملة Vellora',
  'Keep the current editorial images.': 'احتفظ بصور الحملة الحالية.',
  'Choose products': 'اختر المنتجات',
  'Pick images directly from your catalog.': 'اختر الصور مباشرة من كتالوج المنتجات.',
  'Upload images': 'ارفع صوراً',
  'Upload your own optimized campaign art.': 'ارفع صور حملتك الخاصة بعد تحسينها.',
  'Hero image': 'صورة الواجهة',
  'Editorial image': 'صورة تحريرية',
  'Current Vellora campaign image': 'صورة حملة Vellora الحالية',
  'Upload image': 'رفع صورة',
  'Optimizing...': 'جارٍ التحسين...',
  'Changes appear on the storefront immediately after publishing.': 'تظهر التغييرات في المتجر فور نشرها.',
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly language = signal<AppLanguage>((localStorage.getItem('luxestudio-language') as AppLanguage) || 'en');
  constructor() { this.apply(this.language()); }
  translate(value: string): string { return this.language() === 'ar' ? (ARABIC[value] || value) : value; }
  toggle(): void { this.set(this.language() === 'en' ? 'ar' : 'en'); }
  set(language: AppLanguage): void { this.language.set(language); localStorage.setItem('luxestudio-language', language); this.apply(language); }
  private apply(language: AppLanguage): void { document.documentElement.lang = language; document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'; document.body.classList.toggle('rtl', language === 'ar'); }
}
